import React from 'react';

const TOS: React.FC = () => {
    return (
        <div className="flex flex-col min-h-screen">
            <main className="flex-1 container mx-auto px-4 md:px-6 py-8">
              <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
              <div className="space-y-6">
                <section>
                  <h2 className="text-2xl font-semibold mb-3">1. Acceptance of Terms</h2>
                  <p>
                    By accessing or using PRIVATEIA, you agree to be bound by these Terms of Service. If you do not agree
                    to these terms, please do not use our services.
                  </p>
                </section>
                <section>
                  <h2 className="text-2xl font-semibold mb-3">2. Description of Service</h2>
                  <p>
                    PRIVATEIA provides AI-powered tools that run entirely in your web browser. Our services use
                    open-source AI models and perform all processing locally on your device.
                  </p>
                </section>
                <section>
                  <h2 className="text-2xl font-semibold mb-3">3. Privacy and Data Protection</h2>
                  <p>
                    We are committed to protecting your privacy. As our AI tools run entirely in your browser:
                  </p>
                  <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>We do not collect, store, or process any of your personal data or inputs on our servers.</li>
                    <li>All data processing occurs locally on your device.</li>
                    <li>We do not have access to any results generated by the AI tools.</li>
                  </ul>
                </section>
                <section>
                  <h2 className="text-2xl font-semibold mb-3">4. User Responsibilities</h2>
                  <p>As a user of PRIVATEIA, you agree:</p>
                  <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>To use our services only for lawful purposes and in accordance with these Terms.</li>
                    <li>Not to attempt to reverse engineer or extract the AI models used in our tools.</li>
                    <li>To maintain the confidentiality of any sensitive information you process using our tools.</li>
                  </ul>
                </section>
                <section>
                  <h2 className="text-2xl font-semibold mb-3">5. Intellectual Property</h2>
                  <p>
                    The PRIVATEIA platform, including its design, features, and functionality, is owned by us and is
                    protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.
                  </p>
                </section>
                <section>
                  <h2 className="text-2xl font-semibold mb-3">6. Disclaimer of Warranties</h2>
                  <p>
                    PRIVATEIA is provided "as is" and "as available" without any warranties of any kind, either express or
                    implied. We do not warrant that our services will be uninterrupted, error-free, or completely secure.
                  </p>
                </section>
                <section>
                  <h2 className="text-2xl font-semibold mb-3">7. Limitation of Liability</h2>
                  <p>
                    To the fullest extent permitted by law, PRIVATEIA shall not be liable for any indirect, incidental,
                    special, consequential, or punitive damages, or any loss of profits or revenues.
                  </p>
                </section>
                <section>
                  <h2 className="text-2xl font-semibold mb-3">8. Changes to Terms</h2>
                  <p>
                    We reserve the right to modify these Terms of Service at any time. We will provide notice of significant
                    changes by posting a prominent announcement on our website.
                  </p>
                </section>
                <section>
                  <h2 className="text-2xl font-semibold mb-3">9. Contact Information</h2>
                  <p>
                    If you have any questions about these Terms of Service, please contact us at{" "}
                    <a href="mailto:legal@privateia.com" className="text-primary hover:underline">
                      legal@privateia.com
                    </a>
                    .
                  </p>
                </section>
              </div>
            </main>
        </div>
    );
}

export default TOS;